#!/usr/bin/env python3
"""Embeds fonts and logo into vendor/assets.js as base64.

This lets index.html work when opened straight from disk (file://), where
fetch() of local files is blocked by the browser.

Usage: python3 scripts/build_assets.py
"""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

FONTS = {
    "Aileron-Regular": "assets/fonts/Aileron-400-normal.ttf",
    "Aileron-Bold": "assets/fonts/Aileron-700-normal.ttf",
    "Aileron-Italic": "assets/fonts/Aileron-400-italic.ttf",
    "Bungee-Regular": "assets/fonts/Bungee-400-normal.ttf",
}
LOGO = "assets/logo.jpg"


def b64(path):
    return base64.b64encode((ROOT / path).read_bytes()).decode("ascii")


def main():
    data = {
        "fonts": {name: b64(path) for name, path in FONTS.items()},
        "logo": "data:image/jpeg;base64," + b64(LOGO),
    }
    out = ROOT / "vendor" / "assets.js"
    out.write_text(
        "// Generated by scripts/build_assets.py — do not edit by hand.\n"
        "window.ZINE_ASSETS = " + json.dumps(data) + ";\n"
    )
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
